---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: foo
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: vishalchavda999/argocd:v1.0.2
          ports:
            - containerPort: 80
