---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: foo
  labels:
    app: httpd
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd