---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-foo
  namespace: foo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vishal-chavda-esb/argocd-demo.git
    targetRevision: HEAD
    path: environment/stage/k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropogationPolicy=foreground
      - PruneLast=true
      